#!/usr/bin/env bash

echo "stowing dotfiles....."

for folder in $(echo "bin,system,p10k,tmux,nvim,zsh,alacritty,ghostty,bash,git,rofi,vscode,kitty,wezterm,fcitx5,waybar,local-bin,kde,claude" | sed "s/,/ /g"); do
  echo "stowing $folder"
  stow -D $folder
  stow $folder
done
