#!/usr/bin/env zsh


for folder in $(echo "bin,tmux,nvim,zsh,alacritty,ghostty,bash,git,hyprland,rofi,vscode,kitty,wezterm,fcitx5,waybar" | sed "s/,/ /g"); do
  echo "Removing $folder"
  stow -D $folder
done
