#!/usr/bin/env bash

echo "stowing dotfiles....."

for folder in $(echo "bin,p10k,tmux,nvim,zsh,alacritty,vscode,kde" | sed "s/,/ /g"); do
  echo "stowing $folder"
  stow -D $folder
  stow $folder
done
