# You can put your preferred keybinds here
# https://wiki.hyprland.org/Configuring/Binds/
#


# Move focus like vim motion

bind = Ctrl+Super, h,movefocus ,l
bind = Ctrl+Super, l,movefocus ,r
bind = Ctrl+Super, k,movefocus ,u
bind = Ctrl+Super, j,movefocus ,d



#
bindr = Super, r, exec, hyprctl reload; killall ags ydotool; ags & # [hidden]

bind = Super, F, exec, firefox
bind = Super, m, fullscreen, 0
