[preferred]
# Use Hyprland portal for screencast/screenshots/global shortcuts
org.freedesktop.impl.portal.ScreenCast=hyprland
org.freedesktop.impl.portal.Screenshot=hyprland
org.freedesktop.impl.portal.GlobalShortcuts=hyprland

# Use GTK portal for everything else (file picker, open URI, etc)
org.freedesktop.impl.portal.Secret=gnome-keyring
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.AppChooser=gtk
org.freedesktop.impl.portal.Print=gtk
org.freedesktop.impl.portal.Notification=gtk
org.freedesktop.impl.portal.Inhibit=gtk
org.freedesktop.impl.portal.LockDown=gtk

# Default fallback for any other interface
default=gtk
